export const GET_USER_LOCATION = "GET_USER_LOCATION";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SET_USER_LOCATION_ERROR = "SET_USER_LOCATION_ERROR";
export const SET_USER_LOCATION_LOADING = "SET_USER_LOCATION_LOADING";
